# Generated by Django 4.2.3 on 2023-12-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="date_joined",
        ),
    ]
