# Generated by Django 4.2.3 on 2023-12-08 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="identityId",
            new_name="identity_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_instructor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="instructorrate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
