# Generated by Django 4.2.3 on 2023-12-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_identityid_userprofile_identity_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructorrate",
            old_name="rate_date",
            new_name="rate_date_created",
        ),
    ]
